### ISSUE TITLE
Issue in creating a new model

### ISSUE THREAD

**Issue by ZeFon** [glass-dev/examples#1]
Hi ! In the example create_new_model I get the error:

ERROR: negative auto-cls, check accuracy settings
warning: ignoring zero monopole
/home/zefon/.local/lib/python3.8/site-packages/gaussiancl.py:81: RuntimeWarning: divide by zero encountered in divide
  q = np.divide(dx, x, where=(dx != 0), out=np.zeros_like(dx))
WARNING: solution did not converge, inexact transform

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/.local/lib/python3.8/site-packages/glass/core.py:169, in generate(generators, yields)
    168 try:
--> 169     _gencall(g, state)
    170 except StopIteration:

File ~/.local/lib/python3.8/site-packages/glass/core.py:127, in _gencall(generator, state)
    126     yields = getattr(generator, 'yields', None)
--> 127     state[yields] = generator.send(state[receives])
    129 log.info('>>> %s: %s <<<', generator.__name__, timedelta(seconds=time.monotonic()-t))

File ~/.local/lib/python3.8/site-packages/glass/generator.py:30, in WrappedGenerator.send(self, value)
     29 '''call send() on wrapped generator'''
---> 30 return self.generator.send(value)

File ~/.local/lib/python3.8/site-packages/glass/matter.py:77, in lognormal_matter(nside, rng)
     76 '''generate lognormal matter fields from Cls'''
---> 77 yield from generate_lognormal(nside, shift=1., rng=rng)

File ~/.local/lib/python3.8/site-packages/glass/random.py:214, in generate_lognormal(nside, shift, rng)
    213 # get Gaussian random field for gls
--> 214 m = grf.send(gls)
    216 log.info('transforming to lognormal distribution')

File ~/.local/lib/python3.8/site-packages/glass/random.py:131, in generate_gaussian(nside, rng)
    130 if i == 0 and np.any(cl < 0):
--> 131     raise ValueError('negative values in cl')
    132 cov[..., i] = cl if cl is not None else 0

ValueError: negative values in cl

The above exception was the direct cause of the following exception:

GeneratorError                            Traceback (most recent call last)
Input In [4], in <cell line: 5>()
      2 lon, lat, od_flag = np.empty(0), np.empty(0), np.empty(0, dtype=bool)
      4 # simulate and add galaxies in each iteration to lists
----> 5 for it in glass.core.generate(generators):
      6     lon = np.append(lon, it[GAL_LON])
      7     lat = np.append(lat, it[GAL_LAT])

File ~/.local/lib/python3.8/site-packages/glass/core.py:174, in generate(generators, yields)
    172         break
    173     except Exception as e:
--> 174         raise GeneratorError(g, state) from e
    175 else:  # no break
    176     ty = time.monotonic()

GeneratorError: iteration 1: uncaught exception in lognormal_matter

I believe the issue is because the model starts at z=0. When I make it bigger than zero it no longer gives an error.

**Comment by ntessore** [comment]
Hi @ZeFon, thanks for pointing this out!

The underlying problem is with CAMB, which needs `mat_wht_redshift()` and `mat_wht_distance()` to be 0 at z=0 or you get negative Cls. Before, those functions ramped up linearly from z=0 to z=0.1 implicitly. But since other Cl codes don't require this, it is done explicitly now. The examples had not been updated to reflect the change, which is:

```py
    ...
    mat_wht_redshift(zlin=0.1),
    ...
```

Updated examples are building and will hopefully show up soon.
